### PR TITLE
Add eng variant name for 421168827

### PR DESCRIPTION
**Pull request by pathmapper**
Fixes https://github.com/whosonfirst-data/whosonfirst-data/issues/1659.

The same was done for 85673785 in https://github.com/whosonfirst-data/whosonfirst-data/pull/1291, but the locality is still not found searching for "Rathnapura".

Ref https://github.com/whosonfirst-data/whosonfirst-data/issues/1254

### CODE REVIEW

**Comment by stepps00** [comment]
Nice, thanks for the fix @pathmapper!

The changes look good to import.. did you use the Exportify tool on 85673785? Asking because I notice a carriage return at the end of the diff.

**Comment by pathmapper** [comment]
> did you use the Exportify tool on 85673785? Asking because I notice a carriage return at the end of the diff.

@stepps00 no, I just modified the GeoJSON file using the GitHub online editing functionality. I did not modify this line, the carriage return was there after saving the edits. If it's a problem I could try to remove it with a local editor and push the file again.

btw: What's the recommended approach to do such changes? Just using any editor? (never used the  Exportfy tool until now).

**Comment by stepps00** [comment]
Ah, gotcha. Unfortunately edits from the Git UI cause issues with the GeoJSON format (weird carriage return).

I'd recommend checking this branch out locally, making the change in a text editor, then using the wof-expotify tool (found in [this repo](https://github.com/whosonfirst/py-mapzen-whosonfirst-export/)) to validate the record. There is also a [Go version](https://github.com/whosonfirst/go-whosonfirst-export) of this code, too if you're more comfortable with that.

Otherwise, I'd be happy to make the change myself.. but merging your commit would be ideal!

**Comment by pathmapper** [comment]
Thanks @stepps, removed the newline at the end of the file and validated with `wof-validate-properties` and `wof-validate-geometry` from the Python version.

Both of my local text editors are appending a newline at the end of a file by default (if there is none). I had to disable this setting. 

Curious if such a newline at the end of a GeoJSON file would break anything within the WOF ecosystem. That said, the file is also validated by the tool with a newline at the end.

**Comment by stepps00** [comment]
> Curious if such a newline at the end of a GeoJSON file would break anything within the WOF ecosystem. That said, the file is also validated by the tool with a newline at the end.

As long as the file validates using the `wof-*` validation tools, we're good!

**Comment by thisisaaronland** [comment]
@pathmapper With any luck, there will be both a containerized version of the `wof-exportify` tool as well as a publicly available endpoint for "exportify-ing" WOF documents shortly.

There is no hard ETA yet but it is work in progress:

https://github.com/whosonfirst/docker-whosonfirst-exportify

**Comment by pathmapper** [comment]
Thanks @stepps00 and @thisisaaronland

**Pull request merged**
